### PR TITLE
Added option to let a other Account controll the bots

### PR DESCRIPTION
**Pull request by Skeec54**
This should make users be able to use the bot if the id is in the config.json, dosen't have support to delete the message they send, only if they have the manage messages perm

### CODE REVIEW

**Comment by ajmeese7** [comment]
Have you tried running this? It doesn't work at all.

**Comment by Skeec54** [comment]
I have tested it in a discord server and it worked for me

**Comment by ajmeese7** [comment]
Can you explain the exact steps you took to get it working, so I can attempt to replicate it? When I cloned the code and added my tokens the bot stopped responding to commands completely. Perhaps I made a mistake somewhere.

**Comment by Skeec54** [comment]
It works with a token and a client ID, so you use the token for the spam accaunt and use the ID at master_id to controll it

**Comment by Skeec54** [comment]
here you can see it on this [youtube video](https://youtu.be/VN_T174vLjQ) that i made really quick

**Comment by Skeec54** [comment]
so anything new to this now?

**Comment by ajmeese7** [comment]
I am waiting on a response to [this](https://github.com/ajmeese7/spambot/issues/33#issuecomment-690354985) from the original issue creator. From how I understood it, this PR does not satisfy the request, so I am awaiting confirmation from them.

However, this is not a direction I plan on taking the project in, as there has been very little demand so far and the project has done well with its target audience. So if this solves the problem of the person who created the issue, they can use your fork, but I don't see any value being added to the average user with this feature.

**Comment by karsh-kay** [comment]
Why add a specific master id just make it so it accepts commands from any of the accounts of which user token has been provided 
Thats so lame like u r making it difficult when it doesn't need to be

**Comment by karsh-kay** [comment]
Also this code doesn't solve the thing that's mentioned
Try testing it with more than one user accounts 🙄 if u cant understand how loops work that is

**Comment by Skeec54** [comment]
Also if you need help with anything feel free to ask me, i have already coded with discord.js over 3 years so if you have any questions or need help feel free to contact me or add me on discord :)

**Comment by ajmeese7** [comment]
I'm going to close this PR for now, but thank you for the offer! I'm actually starting up a dev space server for people who like to work on stuff like this. Here's the [invite link](https://discord.gg/PxRTQg3) if you're interested, cheers!

**Pull request closed without merging**
